spring:
  application:
    name: projectPP_3.1.1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exampledb?useSSL=false&serverTimezone=UTC
    username: root123
    password: "root123@vlad"

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.security: DEBUG
